# Generated by Django 4.1.7 on 2023-03-15 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0006_remove_post_images_remove_post_videos_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.post')),
            ],
        ),
    ]
