# Generated by Django 4.1.7 on 2023-03-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_friend_from_user_alter_friend_to_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='accepted',
        ),
    ]
