# Generated by Django 4.1.7 on 2023-04-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_friend_from_user_alter_friend_to_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_friend'),
        ),
    ]
